# Generated by Django 2.1.8 on 2021-06-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20160825_1236'),
    ]

    operations = [
    ]
