# Generated by Django 2.1.8 on 2021-06-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210622_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budget', to='budget.Budget'),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='planned',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
