# Generated by Django 2.1.8 on 2021-06-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20210622_0335'),
    ]

    operations = [
    ]
