# Generated by Django 2.1.8 on 2021-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210622_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='slug',
            field=models.SlugField(),
        ),
    ]
