# Generated by Django 2.1.8 on 2021-06-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210622_0645'),
    ]

    operations = [
    ]
