# Generated by Django 2.1.8 on 2021-06-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0009_auto_20210622_0700'),
        ('accounts', '0004_auto_20210622_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_budget', to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=65)),
                ('beneficiary', models.CharField(max_length=50)),
                ('debit', models.BooleanField(default=True)),
                ('transfer', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trans_account', to='accounts.Account')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trans_monthly_budget', to='budget.MonthlyBudget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trans_category', to='transactions.Category')),
            ],
        ),
    ]
